### ISSUE TITLE
Undefined text_train_sub variable in notebook "aml-19-text-data.ipynb" 

### ISSUE THREAD

**Issue by benbrock26** [amueller/COMS4995-s18#17]
Issue) Variable text_train_sub

What is the value of text_train_sub?
There are many cells where the text_train_sub it is used. This variable has never been set or defined in the "aml-19-text-data.ipynb" notebook.

This is the error that I got when I was running the notebook:
NameError: name 'text_train_sub' is not defined

**Comment by amueller** [comment]
Fixed it.
